apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-hooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance-hooks
  template:
    metadata:
      labels:
        app: governance-hooks
    spec:
      containers:
        - name: governance-hooks
          image: governance-hooks:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: governance-hooks
spec:
  selector:
    app: governance-hooks
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
