apiVersion: apps/v1
kind: Deployment
metadata:
  name: objective-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objective-hub
  template:
    metadata:
      labels:
        app: objective-hub
    spec:
      containers:
      - name: objective-hub
        image: objective-hub:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: objective-hub
spec:
  selector:
    app: objective-hub
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
