apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-allocator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-allocator
  template:
    metadata:
      labels:
        app: resource-allocator
    spec:
      containers:
        - name: resource-allocator
          image: resource-allocator:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: resource-allocator
spec:
  selector:
    app: resource-allocator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
