name: CI Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: make build

      - name: Run Tests (Jest Monorepo)
        run: npm test

      - name: Run Linters (Monorepo)
        run: npm run lint